# analysis_options.yaml
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint           # habilita riverpod_lint
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"         # excluir código generado
    - "**/*.realm.dart"

linter:
  rules:
    # Dart efectivo
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true           # usar logger en su lugar
    
    # Legibilidad
    always_declare_return_types: true
    annotate_overrides: true
    
    # Rendimiento Flutter
    use_key_in_widget_constructors: true
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    
    # Seguridad
    avoid_dynamic_calls: true
    cast_nullable_to_non_nullable: true